### ISSUE TITLE
NameError 

### ISSUE THREAD

**Issue by banMo88** [TheLastBen/PPS#11]
happend"Start Stable-Diffusion "part
NameError                                 Traceback (most recent call last)
Cell In [10], line 13
      7 Use_localtunnel = True
      9 # If you have trouble using Gradio server, use this one.
     10 
     11 
     12 #-----------------
---> 13 configf=sd(User, Password, Use_localtunnel, model)
     14 get_ipython().system('python /notebooks/sd/stable-diffusion-webui/webui.py $configf')

NameError: name 'sd' is not defined

**Comment by TheLastBen** [comment]
use the latest notebooks, you'll find them inside "latest_notebooks" folder, copy them to the main workspace

**Comment by banMo88** [comment]
Ok,it works.Thanks.
