### ISSUE TITLE
What is the link I should put in the "Workspace URL" tab?

### ISSUE THREAD

**Issue by Juansigma** [TheLastBen/PPS#3]

**Comment by TheLastBen** [comment]
do a screenshot

**Comment by Juansigma** [comment]
![image](https://user-images.githubusercontent.com/127377346/236642161-1d2122c0-a6a3-421f-ae2f-22295d49fc69.png)

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/PPS
