### ISSUE TITLE
dependencies not found

### ISSUE THREAD

**Issue by m-wilkosz** [TheLastBen/PPS#39]
ppsdeps_311.tar.zst has not been found in TheLastBen/dependencies on HuggingFace.

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[1], line 8
      3 force_reinstall= False
      5 # Set to true only if you want to install the dependencies again.
      6 
      7 #--------------------
----> 8 with open('/dev/null', 'w') as devnull:import requests, os, importlib;sc="mainpaperspaceA1111.py" if os.path.exists('/usr/local/lib/python3.9') else "mainpaperspaceA1111_311.py";open('/notebooks/mainpaperspaceA1111.py', 'wb').write(requests.get('https://huggingface.co/datasets/TheLastBen/PPS/raw/main/Scripts/'+sc).content);os.chdir('/notebooks');import mainpaperspaceA1111;importlib.reload(mainpaperspaceA1111);from mainpaperspaceA1111 import *;Deps(force_reinstall)

File /notebooks/mainpaperspaceA1111.py:45, in Deps(force_reinstall)
     43 call('wget -q -i https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/Dependencies/aptdeps_311.txt', shell=True)
     44 call('dpkg -i *.deb', shell=True, stdout=open('/dev/null', 'w'))
---> 45 depsinst("https://huggingface.co/TheLastBen/dependencies/resolve/main/ppsdeps_311.tar.zst", "/deps/ppsdeps_311.tar.zst")
     46 call('tar -C / --zstd -xf ppsdeps_311.tar.zst', shell=True, stdout=open('/dev/null', 'w'))
     47 os.chdir('/notebooks')

File /notebooks/mainpaperspaceA1111.py:66, in depsinst(url, dst)
     64 file_size = None
     65 req = Request(url, headers={"User-Agent": "torch.hub"})
---> 66 u = urlopen(req)
     67 meta = u.info()
     68 if hasattr(meta, 'getheaders'):

File /usr/lib/python3.11/urllib/request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File /usr/lib/python3.11/urllib/request.py:525, in OpenerDirector.open(self, fullurl, data, timeout)
    523 for processor in self.process_response.get(protocol, []):
    524     meth = getattr(processor, meth_name)
--> 525     response = meth(req, response)
    527 return response

File /usr/lib/python3.11/urllib/request.py:634, in HTTPErrorProcessor.http_response(self, request, response)
    631 # According to RFC 2616, "2xx" code indicates that the client's
    632 # request was successfully received, understood, and accepted.
    633 if not (200 <= code < 300):
--> 634     response = self.parent.error(
    635         'http', request, response, code, msg, hdrs)
    637 return response

File /usr/lib/python3.11/urllib/request.py:563, in OpenerDirector.error(self, proto, *args)
    561 if http_err:
    562     args = (dict, 'default', 'http_error_default') + orig_args
--> 563     return self._call_chain(*args)

File /usr/lib/python3.11/urllib/request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File /usr/lib/python3.11/urllib/request.py:643, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    642 def http_error_default(self, req, fp, code, msg, hdrs):
--> 643     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 404: Not Found

**Comment by Arrozz11** [comment]
I have the same problem.

**Comment by Dissidias** [comment]
+1

**Comment by yhayano-ponotech** [comment]
Same

**Comment by sixpt** [comment]
Same issue here

**Comment by amit4aws** [comment]
@TheLastBen  Can we please get some help on this ?

**Comment by Dissidias** [comment]
Seems like ppsdeps_311.tar.zst was deleted

**Comment by SRagy** [comment]
TheLastBen intentionally broke the configuration. I give a workaround which might be effective for some of you here: https://github.com/TheLastBen/fast-stable-diffusion/issues/2868#issuecomment-2211953469

You can read the rest of the thread for background.

**Comment by amit4aws** [comment]
Thanks for sharing the workaround but it is erroing out at the exact same
place even with your set of files

      7 #--------------------
----> 8 with open('/dev/null', 'w') as devnull:import requests, os,
importlib;sc="sdxllorapps.py" if os.path.exists('/usr/local/lib/python3.9')
else "sdxllorapps_311.py";open('/notebooks/sdxllorapps.py',
'wb').write(requests.get('
https://huggingface.co/datasets/TheLastBen/PPS/raw/main/Scripts/'+sc).content);os.chdir('/notebooks');import
sdxllorapps;importlib.reload(sdxllorapps);from sdxllorapps import
*;Deps(force_reinstall)

File /notebooks/sdxllorapps.py:62, in Deps(force_reinstall)
     60 call('wget -q -i
https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/Dependencies/aptdeps_311.txt',
shell=True)
     61 call('dpkg -i *.deb', shell=True, stdout=open('/dev/null', 'w'))
---> 62 depsinst("
https://huggingface.co/TheLastBen/dependencies/resolve/main/ppsdeps_311.tar.zst",
"/deps/ppsdeps_311.tar.zst")
     63 call('tar -C / --zstd -xf ppsdeps_311.tar.zst', shell=True,
stdout=open('/dev/null', 'w'))
     64 os.chdir('/notebooks')
