### ISSUE TITLE
Is it possible to connect Google Drive in Paperspace to load models, LoRA, VAE, Embeddings, Textual Inversions? How do I upload these files to Paperspace?

### ISSUE THREAD

**Issue by Juansigma** [TheLastBen/PPS#4]
![image](https://user-images.githubusercontent.com/127377346/236645126-2200a3e9-96d8-40fe-b273-899b458bf25d.png)
![image](https://user-images.githubusercontent.com/127377346/236645154-59f309d9-0ac1-4aaf-b78a-4ffe776c42d8.png)

**Comment by TheLastBen** [comment]
share the gdrive folder, then download it with `!gdown --folder (link)`

click on the jupyter lab icon on the left panel for an easier interface

**Comment by Juansigma** [comment]
![image](https://user-images.githubusercontent.com/127377346/236646314-6747aa15-b9e3-489a-aeae-8d360899954c.png)

**Comment by TheLastBen** [comment]
remove the () around the link
