### ISSUE TITLE
Even with all permissions on Google Drive, sometimes Paperspace does not recognize them and does not download LoRA

### ISSUE THREAD

**Issue by Juansigma** [TheLastBen/PPS#6]
Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:
(link)

**Comment by TheLastBen** [comment]
if you download the files too many times, google will restrict the download

**Comment by Juansigma** [comment]
Does this happen when I upload multiple files at once, or when I upload a lot? I'm currently going 10 out of 10

**Comment by TheLastBen** [comment]
if you download the same link many times, it gets locked and you won't be able to download it through gdown, a workaround is to make a copy of the file/folder, then download it with the new link

**Comment by Juansigma** [comment]
Another solution, but slower, is to drag each file to the appropriate folders, it is recommended to do it only with LoRA and small files, because uploading that way is very slow
